name: continuous integration

on: push

env:
  CORE_LIGHTNING_VERSION: '24.08.2'
  GO_VERSION: '1.23'
  PYTHON_VERSION: '3.13'

jobs:
  isolation-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make trustedcoin
      - run: go test -v

  integration-tests:
    name: Integration tests on Bitcoin Core ${{ matrix.bitcoin-core-version }}
    runs-on: ubuntu-24.04
    env:
      BITCOIN_CORE_VERSION: ${{ matrix.bitcoin-core-version }}
      VALGRIND: 0
    strategy:
      fail-fast: false
      matrix:
        bitcoin-core-version:
          - '25.2'
          - '26.2'
          - '27.2'
          - '28.0'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: make trustedcoin
      - run: .github/scripts/install-bitcoind.sh
      - run: .github/scripts/install-cln.sh
      - run: |
          python -m venv venv
          echo "venv/bin" >> $GITHUB_PATH
          source venv/bin/activate
          pip install pip-tools
          pip-compile --strip-extras
          pip-sync
      - run: pytest
